# pre-commit autoupdate

fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # isort - sort import statements
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: \.(py)$
        args: [--settings-path=pyproject.toml]  # ["--profile", "black" ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --fix ]  # run linter
      - id: ruff-format  # run formatter


  #### OPTIONAL: for keeping syntax more current

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py311-plus]    # NOTE: SET TO HOME ASSISTANT VERSION

  - repo: https://github.com/dosisod/refurb
    rev: v2.0.0
    hooks:
      - id: refurb              # NOTE: Update pyproject.toml to match HA Python version
