[tool.isort]
force_to_top = [ "logging" ]
balanced_wrapping = true

[tool.ruff]
line-length = 88
indent-width = 4
lint.ignore = [
       "F405"  # * imports
]

[tool.ruff.format]
quote-style = "single" # Use a single quote instead of double

[tool.pycln]
all = true

[tool.refurb]
python_version = "3.11"
quiet = true
ignore = [ "FURB184" ]
